name: Build & Push Docker Image

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'CHANGELOG.md'
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4
        with:
          node-version: 20.15
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Release
        run: |
          npm ci
          npx semantic-release